apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: tako-postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/takodotid/postgresql:16-4f9b0333b7a303bf61ab0bce98c73e184c64bddf
    - major: 17
      image: ghcr.io/takodotid/postgresql:17-4f9b0333b7a303bf61ab0bce98c73e184c64bddf
