apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: tako-postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/takodotid/postgresql:16.11-9f80531dfbd0ce4fd317196fc5430c48fba874cb
    - major: 17
      image: ghcr.io/takodotid/postgresql:17.7-9f80531dfbd0ce4fd317196fc5430c48fba874cb
    - major: 18
      image: ghcr.io/takodotid/postgresql:18.1-9f80531dfbd0ce4fd317196fc5430c48fba874cb
