apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: tako-postgresql
spec:
  images:
    - major: 16
      image: ghcr.io/takodotid/postgresql:16.13-3791f530562ba37455fca546a161e389dbbb33cd
    - major: 17
      image: ghcr.io/takodotid/postgresql:17.9-3791f530562ba37455fca546a161e389dbbb33cd
    - major: 18
      image: ghcr.io/takodotid/postgresql:18.3-3791f530562ba37455fca546a161e389dbbb33cd
